
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button btnsumar;
	private global::Gtk.Button btndiv;
	private global::Gtk.Label lblnum3;
	private global::Gtk.Entry txtnum3;
	private global::Gtk.Label lblnum2;
	private global::Gtk.Entry txtnum2;
	private global::Gtk.Entry txtnum1;
	private global::Gtk.Label lblnum1;
	private global::Gtk.Button btnrestar;
	private global::Gtk.Button btnmulti;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnsumar = new global::Gtk.Button ();
		this.btnsumar.CanFocus = true;
		this.btnsumar.Name = "btnsumar";
		this.btnsumar.UseUnderline = true;
		this.btnsumar.Label = global::Mono.Unix.Catalog.GetString ("SUMAR");
		this.fixed1.Add (this.btnsumar);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnsumar]));
		w1.X = 14;
		w1.Y = 208;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btndiv = new global::Gtk.Button ();
		this.btndiv.CanFocus = true;
		this.btndiv.Name = "btndiv";
		this.btndiv.UseUnderline = true;
		this.btndiv.Label = global::Mono.Unix.Catalog.GetString ("DIVIDIR");
		this.fixed1.Add (this.btndiv);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btndiv]));
		w2.X = 292;
		w2.Y = 207;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblnum3 = new global::Gtk.Label ();
		this.lblnum3.Name = "lblnum3";
		this.lblnum3.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.fixed1.Add (this.lblnum3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblnum3]));
		w3.X = 66;
		w3.Y = 127;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtnum3 = new global::Gtk.Entry ();
		this.txtnum3.CanFocus = true;
		this.txtnum3.Name = "txtnum3";
		this.txtnum3.IsEditable = true;
		this.txtnum3.InvisibleChar = '●';
		this.fixed1.Add (this.txtnum3);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtnum3]));
		w4.X = 187;
		w4.Y = 134;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblnum2 = new global::Gtk.Label ();
		this.lblnum2.Name = "lblnum2";
		this.lblnum2.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 2");
		this.fixed1.Add (this.lblnum2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblnum2]));
		w5.X = 65;
		w5.Y = 77;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtnum2 = new global::Gtk.Entry ();
		this.txtnum2.CanFocus = true;
		this.txtnum2.Name = "txtnum2";
		this.txtnum2.IsEditable = true;
		this.txtnum2.InvisibleChar = '●';
		this.fixed1.Add (this.txtnum2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtnum2]));
		w6.X = 186;
		w6.Y = 73;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtnum1 = new global::Gtk.Entry ();
		this.txtnum1.CanFocus = true;
		this.txtnum1.Name = "txtnum1";
		this.txtnum1.IsEditable = true;
		this.txtnum1.InvisibleChar = '●';
		this.fixed1.Add (this.txtnum1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtnum1]));
		w7.X = 185;
		w7.Y = 26;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblnum1 = new global::Gtk.Label ();
		this.lblnum1.Name = "lblnum1";
		this.lblnum1.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 1");
		this.fixed1.Add (this.lblnum1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblnum1]));
		w8.X = 66;
		w8.Y = 31;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnrestar = new global::Gtk.Button ();
		this.btnrestar.CanFocus = true;
		this.btnrestar.Name = "btnrestar";
		this.btnrestar.UseUnderline = true;
		this.btnrestar.Label = global::Mono.Unix.Catalog.GetString ("RESTA");
		this.fixed1.Add (this.btnrestar);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnrestar]));
		w9.X = 106;
		w9.Y = 207;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnmulti = new global::Gtk.Button ();
		this.btnmulti.CanFocus = true;
		this.btnmulti.Name = "btnmulti";
		this.btnmulti.UseUnderline = true;
		this.btnmulti.Label = global::Mono.Unix.Catalog.GetString ("MULTIPLICAR");
		this.fixed1.Add (this.btnmulti);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnmulti]));
		w10.X = 181;
		w10.Y = 205;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 389;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnsumar.Clicked += new global::System.EventHandler (this.OnBtnsumarClicked);
		this.btndiv.Clicked += new global::System.EventHandler (this.OnBtndivClicked);
		this.btnrestar.Clicked += new global::System.EventHandler (this.OnBtnrestarClicked);
		this.btnmulti.Clicked += new global::System.EventHandler (this.OnBtnmultiClicked);
	}
}
